import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-telecom-tax-surcharge-audit",
  "engine": "recovery",
  "title": "Telecom Tax & Surcharge Audit",
  "shortTitle": "Telecom Tax and Surcharge Audit",
  "tagline": "Audit telecom taxes and regulatory surcharges against service type, jurisdiction, exemption, and contribution rules.",
  "industry": "Telecom Expense Recovery",
  "buyer": "Enterprises, carriers, and communications platforms",
  "uiPort": 4688,
  "apiPort": 5688,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Telecom Tax & Surcharge Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds in one accountable workflow. Audit telecom taxes and regulatory surcharges against service type, jurisdiction, exemption, and contribution rules.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Telecom Tax & Surcharge Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("carrier-invoice-ingestion","TTS01","Carrier invoice ingestion","Execute carrier invoice ingestion using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed carrier invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Carrier invoice ingestion Reference","text","TTS01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("service-product-classification","TTS02","Service product classification","Execute service product classification using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed service product classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Service product classification Reference","text","TTS02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("service-address-validation","TTS03","Service address validation","Execute service address validation using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed service address validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Service address validation Reference","text","TTS03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("jurisdiction-mapping","TTS04","Jurisdiction mapping","Execute jurisdiction mapping using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed jurisdiction mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Jurisdiction mapping Reference","text","TTS04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("federal-usf-calculation","TTS05","Federal USF calculation","Execute federal usf calculation using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed federal usf calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Federal USF calculation Reference","text","TTS05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("state-usf-calculation","TTS06","State USF calculation","Execute state usf calculation using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed state usf calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","State USF calculation Reference","text","TTS06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("911-surcharge-validation","TTS07","911 surcharge validation","Execute 911 surcharge validation using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed 911 surcharge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","911 surcharge validation Reference","text","TTS07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("gross-receipts-tax-review","TTS08","Gross receipts tax review","Execute gross receipts tax review using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed gross receipts tax review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Gross receipts tax review Reference","text","TTS08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("utility-user-tax-review","TTS09","Utility user tax review","Execute utility user tax review using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed utility user tax review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Utility user tax review Reference","text","TTS09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("internet-access-exemption","TTS10","Internet access exemption","Execute internet access exemption using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed internet access exemption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Internet access exemption Reference","text","TTS10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("resale-exemption","TTS11","Resale exemption","Execute resale exemption using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed resale exemption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Resale exemption Reference","text","TTS11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("overcharge-calculation","TTS12","Overcharge calculation","Execute overcharge calculation using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed overcharge calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Overcharge calculation Reference","text","TTS12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("carrier-refund-request","TTS13","Carrier refund request","Execute carrier refund request using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed carrier refund request decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Carrier refund request Reference","text","TTS13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("tax-authority-claim-workflow","TTS14","Tax authority claim workflow","Execute tax authority claim workflow using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed tax authority claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Tax authority claim workflow Reference","text","TTS14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]}),
feature("service-jurisdiction-analytics","TTS15","Service jurisdiction analytics","Execute service jurisdiction analytics using telecom invoices, service addresses, product codes, jurisdiction mapping, federal and state taxes, USF, regulatory fees, exemptions, credits, and refunds.","Produce a governed service jurisdiction analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Service Account","text","Carrier / Service Account · Standard Case"],["caseReference","Service jurisdiction analytics Reference","text","TTS15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1126250],["supportedAmount","Evidence-Supported Amount","currency",946050],["domainDriver","Charge Type","select","USF",["USF","State telecom tax","911 surcharge"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Carrier invoice ingestion case","Service product classification case","Service address validation case","Jurisdiction mapping case","Federal USF calculation case"]})
]);
